version : '3.8'
services :
    api-service :
        build : ./API/
        volumes :
            - ./API/:/usr/src/app/
        ports :
            - 5000:5000
        environment:
            PORT : 5000
            FLASK_DEBUG : 1